version: '3.4'

services:
  keyboardapi:
    image: ${DOCKER_REGISTRY-}keyboardapi
    build:
      context: .
      dockerfile: KeyboardAPI/Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - keyboards-loadbalancer

  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - users-loadbalancer

  users-loadbalancer:
    image: ${DOCKER_REGISTRY-}loadbalancer
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    ports:
      - 9080:80

  keyboards-loadbalancer:
    image: ${DOCKER_REGISTRY-}loadbalancer
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    ports:
      - 9082:80