name: dockerhub-deploy

on:
  push: 
    branches: ["master"]
  workflow_dispatch:

env:
  DOCERHUB_USERNAME : adm14
  DOCKERHUB_PASSWORD : ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  logIn:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: docker login -u $DOCERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  build:
    runs-on: ubuntu-latest
    needs: logIn
    steps:
    - name: Build Docker images
      run: docker-compose build
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Push Docker images
      run: docker-compose push
    